CREATE TABLE IF NOT EXISTS rooms (id SERIAL PRIMARY KEY, number VARCHAR(10) NOT NULL, type VARCHAR(20) NOT NULL, beds INTEGER NOT NULL, occupied INTEGER NOT NULL, status VARCHAR(20) NOT NULL);
CREATE TABLE IF NOT EXISTS bookings (id SERIAL PRIMARY KEY, guest_name VARCHAR(80) NOT NULL, room_number VARCHAR(10) NOT NULL, check_in DATE NOT NULL, check_out DATE NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments (id SERIAL PRIMARY KEY, guest_name VARCHAR(80) NOT NULL, invoice VARCHAR(20) NOT NULL, amount DECIMAL(10, 2) NOT NULL, status VARCHAR(20) NOT NULL, due_date DATE NOT NULL);
CREATE TABLE IF NOT EXISTS staff (id SERIAL PRIMARY KEY, name VARCHAR(80) NOT NULL, role VARCHAR(40) NOT NULL, shift VARCHAR(40) NOT NULL, on_duty BOOLEAN DEFAULT true);
CREATE TABLE IF NOT EXISTS maintenance_tickets (id SERIAL PRIMARY KEY, issue VARCHAR(120) NOT NULL, room_number VARCHAR(10) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS occupancy_trend (id SERIAL PRIMARY KEY, month_label VARCHAR(12) NOT NULL, rate INTEGER NOT NULL, sort_order INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS room_status_overview (id SERIAL PRIMARY KEY, label VARCHAR(30) NOT NULL, value INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(120) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'user', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hostels (id SERIAL PRIMARY KEY, owner_id INTEGER, name VARCHAR(100) NOT NULL, area VARCHAR(80) NOT NULL, city VARCHAR(80) NOT NULL, address VARCHAR(180) NOT NULL, lat DECIMAL(10, 6) NOT NULL, lng DECIMAL(10, 6) NOT NULL, gender VARCHAR(20) NOT NULL DEFAULT 'co-ed', description TEXT, phone VARCHAR(40), email VARCHAR(120), approved BOOLEAN DEFAULT false, is_active BOOLEAN DEFAULT true, FOREIGN KEY (owner_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS hostel_rooms (id SERIAL PRIMARY KEY, hostel_id INTEGER NOT NULL, room_type VARCHAR(20) NOT NULL, occupants_per_room INTEGER NOT NULL, beds_total INTEGER NOT NULL, beds_available INTEGER NOT NULL, available_from DATE NOT NULL, available_to DATE NOT NULL, rent DECIMAL(10, 2) NOT NULL, FOREIGN KEY (hostel_id) REFERENCES hostels(id));
CREATE TABLE IF NOT EXISTS hostel_images (id SERIAL PRIMARY KEY, hostel_id INTEGER NOT NULL, url VARCHAR(255) NOT NULL, FOREIGN KEY (hostel_id) REFERENCES hostels(id));
CREATE TABLE IF NOT EXISTS hostel_facilities (id SERIAL PRIMARY KEY, hostel_id INTEGER NOT NULL, name VARCHAR(80) NOT NULL, FOREIGN KEY (hostel_id) REFERENCES hostels(id));
CREATE TABLE IF NOT EXISTS hostel_rules (id SERIAL PRIMARY KEY, hostel_id INTEGER NOT NULL, rule VARCHAR(160) NOT NULL, FOREIGN KEY (hostel_id) REFERENCES hostels(id));
CREATE TABLE IF NOT EXISTS owner_subscriptions (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL, plan_id VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, payment_method VARCHAR(40) NOT NULL, transaction_ref VARCHAR(120), started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMP NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS user_favorites (user_id INTEGER NOT NULL, hostel_id INTEGER NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, hostel_id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (hostel_id) REFERENCES hostels(id));
INSERT INTO users (name, email, password_hash, role) VALUES ('Admin User', 'admin@stayscout.pk', '$2a$10$3Qm4JUiQ9iC1X1XbBObh3eVbEPYmn6v2w2rYtEU/3DrHh5V3hXgQW', 'admin');
INSERT INTO users (name, email, password_hash, role) VALUES ('Ayesha Owner', 'owner@stayscout.pk', '$2a$10$3Qm4JUiQ9iC1X1XbBObh3eVbEPYmn6v2w2rYtEU/3DrHh5V3hXgQW', 'owner');
INSERT INTO rooms (number, type, beds, occupied, status) VALUES ('A-01', 'Shared', 4, 3, 'Occupied');
INSERT INTO rooms (number, type, beds, occupied, status) VALUES ('A-02', 'Single', 1, 1, 'Occupied');
INSERT INTO rooms (number, type, beds, occupied, status) VALUES ('B-03', 'Shared', 6, 4, 'Available');
INSERT INTO rooms (number, type, beds, occupied, status) VALUES ('C-05', 'Private', 2, 2, 'Maintenance');
INSERT INTO bookings (guest_name, room_number, check_in, check_out, status) VALUES ('Ayesha Khan', 'B-12', '2026-03-10', '2026-03-13', 'Confirmed');
INSERT INTO bookings (guest_name, room_number, check_in, check_out, status) VALUES ('Imran Ali', 'A-07', '2026-03-11', '2026-03-12', 'Pending');
INSERT INTO bookings (guest_name, room_number, check_in, check_out, status) VALUES ('Sara Malik', 'C-05', '2026-03-05', '2026-03-12', 'Checked-in');
INSERT INTO payments (guest_name, invoice, amount, status, due_date) VALUES ('Hamza Ahmed', 'INV-1102', 12500, 'Overdue', '2026-03-14');
INSERT INTO payments (guest_name, invoice, amount, status, due_date) VALUES ('Noor Fatima', 'INV-1103', 9800, 'Due', '2026-03-16');
INSERT INTO payments (guest_name, invoice, amount, status, due_date) VALUES ('Bilal Raza', 'INV-1104', 7200, 'Paid', '2026-03-03');
INSERT INTO staff (name, role, shift, on_duty) VALUES ('Rizwan', 'Front Desk', '8:00 AM - 4:00 PM', true);
INSERT INTO staff (name, role, shift, on_duty) VALUES ('Saad', 'Security', '10:00 AM - 6:00 PM', true);
INSERT INTO staff (name, role, shift, on_duty) VALUES ('Nimra', 'Housekeeping', '9:00 AM - 5:00 PM', true);
INSERT INTO staff (name, role, shift, on_duty) VALUES ('Farah', 'Maintenance', '11:00 AM - 7:00 PM', false);
INSERT INTO maintenance_tickets (issue, room_number, status) VALUES ('AC not cooling', 'C-05', 'Open');
INSERT INTO maintenance_tickets (issue, room_number, status) VALUES ('Leaking tap', 'B-03', 'In Progress');
INSERT INTO maintenance_tickets (issue, room_number, status) VALUES ('Window lock', 'A-02', 'Resolved');
INSERT INTO occupancy_trend (month_label, rate, sort_order) VALUES ('Jan', 72, 1);
INSERT INTO occupancy_trend (month_label, rate, sort_order) VALUES ('Feb', 68, 2);
INSERT INTO occupancy_trend (month_label, rate, sort_order) VALUES ('Mar', 78, 3);
INSERT INTO occupancy_trend (month_label, rate, sort_order) VALUES ('Apr', 81, 4);
INSERT INTO occupancy_trend (month_label, rate, sort_order) VALUES ('May', 75, 5);
INSERT INTO occupancy_trend (month_label, rate, sort_order) VALUES ('Jun', 84, 6);
INSERT INTO room_status_overview (label, value) VALUES ('Clean', 38);
INSERT INTO room_status_overview (label, value) VALUES ('Needs Cleaning', 12);
INSERT INTO room_status_overview (label, value) VALUES ('Maintenance', 5);
INSERT INTO hostels (owner_id, name, area, city, address, lat, lng, gender, description, phone, email, approved, is_active) VALUES (2, 'City Center Hostel', 'Gulberg', 'Lahore', '12 Main Blvd, Gulberg, Lahore', 31.519800, 74.352200, 'girls', 'Bright rooms and fast WiFi in the heart of the city.', '+92-300-1112233', 'hello@citycenter.pk', true, true);
INSERT INTO hostels (owner_id, name, area, city, address, lat, lng, gender, description, phone, email, approved, is_active) VALUES (2, 'Metro Stay', 'Johar Town', 'Lahore', 'Street 5, Johar Town, Lahore', 31.468700, 74.273700, 'boys', 'Affordable shared rooms with easy transport.', '+92-300-2223344', 'contact@metrostay.pk', true, true);
INSERT INTO hostels (owner_id, name, area, city, address, lat, lng, gender, description, phone, email, approved, is_active) VALUES (2, 'Green View Hostel', 'Model Town', 'Lahore', 'Block C, Model Town, Lahore', 31.482500, 74.323600, 'co-ed', 'Family-run hostel with premium facilities.', '+92-300-3334455', 'stay@greenview.pk', true, true);
INSERT INTO hostels (owner_id, name, area, city, address, lat, lng, gender, description, phone, email, approved, is_active) VALUES (2, 'Canal Side Hostel', 'DHA Phase 5', 'Lahore', 'Near Canal Road, Lahore', 31.471200, 74.401800, 'girls', 'Quiet and secure hostel near the canal.', '+92-300-4445566', 'info@canalside.pk', true, true);
INSERT INTO hostels (owner_id, name, area, city, address, lat, lng, gender, description, phone, email, approved, is_active) VALUES (2, 'Skyline Residences', 'Wapda Town', 'Lahore', 'Phase 1, Wapda Town, Lahore', 31.451200, 74.274100, 'boys', 'Modern hostel with curated study spaces.', '+92-300-5556677', 'hello@skyline.pk', true, true);
INSERT INTO hostels (owner_id, name, area, city, address, lat, lng, gender, description, phone, email, approved, is_active) VALUES (2, 'Riverfront Lodge', 'Bahria Town', 'Lahore', 'Block B, Bahria Town, Lahore', 31.361200, 74.180200, 'co-ed', 'Comfortable rooms near the main boulevard.', '+92-300-6667788', 'stay@riverfront.pk', true, true);
INSERT INTO hostels (owner_id, name, area, city, address, lat, lng, gender, description, phone, email, approved, is_active) VALUES (2, 'Cedar House', 'Cantt', 'Lahore', 'Mall Road, Cantt, Lahore', 31.548100, 74.364900, 'girls', 'Secure hostel with premium amenities.', '+92-300-7778899', 'info@cedarhouse.pk', true, true);
INSERT INTO hostel_rooms (hostel_id, room_type, occupants_per_room, beds_total, beds_available, available_from, available_to, rent) VALUES (1, 'shared', 4, 20, 6, '2026-03-12', '2026-06-30', 4500);
INSERT INTO hostel_rooms (hostel_id, room_type, occupants_per_room, beds_total, beds_available, available_from, available_to, rent) VALUES (1, 'single', 1, 8, 2, '2026-03-20', '2026-06-30', 8500);
INSERT INTO hostel_rooms (hostel_id, room_type, occupants_per_room, beds_total, beds_available, available_from, available_to, rent) VALUES (2, 'shared', 6, 30, 10, '2026-03-14', '2026-05-31', 3800);
INSERT INTO hostel_rooms (hostel_id, room_type, occupants_per_room, beds_total, beds_available, available_from, available_to, rent) VALUES (2, 'private', 2, 10, 4, '2026-03-10', '2026-07-15', 7200);
INSERT INTO hostel_rooms (hostel_id, room_type, occupants_per_room, beds_total, beds_available, available_from, available_to, rent) VALUES (3, 'single', 1, 6, 1, '2026-03-22', '2026-06-15', 9200);
INSERT INTO hostel_rooms (hostel_id, room_type, occupants_per_room, beds_total, beds_available, available_from, available_to, rent) VALUES (3, 'shared', 4, 18, 5, '2026-03-18', '2026-05-20', 5200);
INSERT INTO hostel_rooms (hostel_id, room_type, occupants_per_room, beds_total, beds_available, available_from, available_to, rent) VALUES (4, 'shared', 3, 12, 3, '2026-03-15', '2026-06-10', 6100);
